pipelines:
  default:
    - step:
        script:
          # Install dependencies.
          - sudo apt-get update
          - sudo apt-get -y install mercurial python2.7 python-matplotlib python-simplejson realpath
          # Use new pip version since Ubuntu's pip version causes problems.
          - wget https://bootstrap.pypa.io/get-pip.py
          - sudo python get-pip.py
          - sudo pip install -U pep8 pyflakes pytest sphinx vulture

          # Print information about environment.
          - python --version
          - python -c "import sys; print(sys.getfilesystemencoding())"
          - python -c "import locale; print(locale.getlocale())"

          - ./tests/run-tests
